ci: force git to fetch depth 500 so that 'git describe --tags' works.
Current error:

Run TAG=$(git describe --tags)
fatal: No names found, cannot describe anything.
Error: Process completed with exit code 128.